name: testing, building
on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install module
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: unit testing
        run: npm run test:unit